title: "Modified Attribution License (MAL) v1.0"
description: "An open and flexible license allowing free use, distribution, modification, and commercialization with attribution rules."
theme: jekyll-theme-cayman
github:
  is_project_page: true
